export const FORECAST_LOCALES = {
  es: 'es-ES', ca: 'ca-ES', en: 'en-GB', fr: 'fr-FR', it: 'it-IT', pt: 'pt-PT'
};

const COPY = {
  es: {
    guideUntranslated: 'Explicación disponible en castellano.', pageTitle: 'Predicción meteorológica AROME | MeteoLabX', title: 'Predicción numérica', subtitle: 'Mapas de modelos meteorológicos y diagnósticos de MeteoLabX.', modelConfig: 'Configuración del modelo', model: 'Modelo', latestRun: 'Última pasada', maps: 'Mapas', selected: 'seleccionados', fields: 'campos', diagnostics: 'diagnósticos MLX', search: 'Buscar variable…', searchMap: 'Buscar mapa', mapSelector: 'Selector de mapas', available: 'Disponible', complete: 'Completa', completed: 'Completo', pending: 'Pendiente', connecting: 'Conectando…', backendUnavailable: 'Backend {model} no disponible', catalogTimeout: 'El catálogo de {model} ha tardado demasiado', mapsAvailable: '{available} de {total} mapas disponibles', hoursAvailable: '{available} de {total} horas disponibles', mlxSymbol: 'El símbolo MLX identifica los mapas calculados por MeteoLabX.', calculatedBy: 'Calculado por MeteoLabX', mlxDiagnostic: 'Diagnóstico calculado por MeteoLabX', noneSelected: 'Ningún mapa seleccionado', valid: 'Válido', downloadPng: 'Descargar PNG', downloadMapPng: 'Descargar el mapa en PNG', fullscreen: 'Pantalla completa', windLevel: 'Nivel vertical del viento', level: 'Nivel', aboveGround: 'Sobre terreno', isobaric: 'Isobárico', loading: 'Cargando {product}', downloading: 'Descargando el mapa ya calculado…', calculating: 'Calculando {product}', workerPending: 'El modelo ya ha publicado esta hora. MeteoLabX la añadirá automáticamente al terminar el worker.', loadError: 'No se pudo cargar el mapa real', previousHourTry: 'Probar la hora anterior', changeUnits: 'Cambiar unidades', units: 'Unidades', previousHour: 'Hora anterior', nextHour: 'Hora siguiente', pause: 'Pausar', play: 'Reproducir', forecastHour: 'Hora prevista', hourAvailable: '{time} UTC disponible', hourPending: '{time} UTC pendiente', viewedMap: 'Mapa visualizado', nativeField: 'Campo {model}', what: 'Qué representa', interpretation: 'Interpretación', calculation: 'Cálculo', sources: 'Base documental', refreshRun: 'Actualizar RUN', theme: 'Cambiar tema', layers: 'Capas del mapa', zoom: 'Controles de zoom', zoomIn: 'Acercar mapa', zoomOut: 'Alejar mapa', resetView: 'Restablecer encuadre', interactiveMap: 'Mapa interactivo de {product}'
  },
  ca: {
    guideUntranslated: 'Aquesta explicació encara no està traduïda i es mostra en castellà.', pageTitle: 'Predicció meteorològica AROME | MeteoLabX', title: 'Predicció numèrica', subtitle: 'Mapes de models meteorològics i diagnòstics de MeteoLabX.', modelConfig: 'Configuració del model', model: 'Model', latestRun: 'Darrera passada', maps: 'Mapes', selected: 'seleccionats', fields: 'camps', diagnostics: 'diagnòstics MLX', search: 'Cerca una variable…', searchMap: 'Cerca un mapa', mapSelector: 'Selector de mapes', available: 'Disponible', complete: 'Completa', completed: 'Complet', pending: 'Pendent', connecting: 'Connectant…', backendUnavailable: 'Backend {model} no disponible', catalogTimeout: 'El catàleg de {model} ha trigat massa', mapsAvailable: '{available} de {total} mapes disponibles', hoursAvailable: '{available} de {total} hores disponibles', mlxSymbol: 'El símbol MLX identifica els mapes calculats per MeteoLabX.', calculatedBy: 'Calculat per MeteoLabX', mlxDiagnostic: 'Diagnòstic calculat per MeteoLabX', noneSelected: 'Cap mapa seleccionat', valid: 'Vàlid', downloadPng: 'Descarrega PNG', downloadMapPng: 'Descarrega el mapa en PNG', fullscreen: 'Pantalla completa', windLevel: 'Nivell vertical del vent', level: 'Nivell', aboveGround: 'Sobre el terreny', isobaric: 'Isobàric', loading: 'Carregant {product}', downloading: 'Descarregant el mapa ja calculat…', calculating: 'Calculant {product}', workerPending: 'El model ja ha publicat aquesta hora. MeteoLabX l’afegirà automàticament quan acabi el worker.', loadError: 'No s’ha pogut carregar el mapa real', previousHourTry: 'Prova l’hora anterior', changeUnits: 'Canvia les unitats', units: 'Unitats', previousHour: 'Hora anterior', nextHour: 'Hora següent', pause: 'Pausa', play: 'Reprodueix', forecastHour: 'Hora prevista', hourAvailable: '{time} UTC disponible', hourPending: '{time} UTC pendent', viewedMap: 'Mapa visualitzat', nativeField: 'Camp {model}', what: 'Què representa', interpretation: 'Interpretació', calculation: 'Càlcul', sources: 'Base documental', refreshRun: 'Actualitza el RUN', theme: 'Canvia el tema', layers: 'Capes del mapa', zoom: 'Controls de zoom', zoomIn: 'Apropa el mapa', zoomOut: 'Allunya el mapa', resetView: 'Restableix l’enquadrament', interactiveMap: 'Mapa interactiu de {product}'
  },
  en: {
    guideUntranslated: 'This explanation has not been translated yet and is shown in Spanish.', pageTitle: 'AROME weather forecast | MeteoLabX', title: 'Numerical forecast', subtitle: 'Weather-model maps and MeteoLabX diagnostics.', modelConfig: 'Model settings', model: 'Model', latestRun: 'Latest run', maps: 'Maps', selected: 'selected', fields: 'fields', diagnostics: 'MLX diagnostics', search: 'Search variable…', searchMap: 'Search map', mapSelector: 'Map selector', available: 'Available', complete: 'Complete', completed: 'Complete', pending: 'Pending', connecting: 'Connecting…', backendUnavailable: '{model} backend unavailable', catalogTimeout: 'The {model} catalogue took too long to respond', mapsAvailable: '{available} of {total} maps available', hoursAvailable: '{available} of {total} hours available', mlxSymbol: 'The MLX symbol identifies maps calculated by MeteoLabX.', calculatedBy: 'Calculated by MeteoLabX', mlxDiagnostic: 'Diagnostic calculated by MeteoLabX', noneSelected: 'No map selected', valid: 'Valid', downloadPng: 'Download PNG', downloadMapPng: 'Download map as PNG', fullscreen: 'Full screen', windLevel: 'Wind vertical level', level: 'Level', aboveGround: 'Above ground', isobaric: 'Isobaric', loading: 'Loading {product}', downloading: 'Downloading the precomputed map…', calculating: 'Calculating {product}', workerPending: 'The model has published this hour. MeteoLabX will add it automatically when the worker finishes.', loadError: 'The live map could not be loaded', previousHourTry: 'Try the previous hour', changeUnits: 'Change units', units: 'Units', previousHour: 'Previous hour', nextHour: 'Next hour', pause: 'Pause', play: 'Play', forecastHour: 'Forecast hour', hourAvailable: '{time} UTC available', hourPending: '{time} UTC pending', viewedMap: 'Map shown', nativeField: '{model} field', what: 'What it shows', interpretation: 'Interpretation', calculation: 'Calculation', sources: 'References', refreshRun: 'Refresh run', theme: 'Change theme', layers: 'Map layers', zoom: 'Zoom controls', zoomIn: 'Zoom in', zoomOut: 'Zoom out', resetView: 'Reset view', interactiveMap: 'Interactive map of {product}'
  },
  fr: {
    guideUntranslated: 'Cette explication n’est pas encore traduite et s’affiche en espagnol.', pageTitle: 'Prévision météo AROME | MeteoLabX', title: 'Prévision numérique', subtitle: 'Cartes de modèles météorologiques et diagnostics MeteoLabX.', modelConfig: 'Configuration du modèle', model: 'Modèle', latestRun: 'Dernier run', maps: 'Cartes', selected: 'sélectionnées', fields: 'champs', diagnostics: 'diagnostics MLX', search: 'Rechercher une variable…', searchMap: 'Rechercher une carte', mapSelector: 'Sélecteur de cartes', available: 'Disponible', complete: 'Complet', completed: 'Complet', pending: 'En attente', connecting: 'Connexion…', backendUnavailable: 'Backend {model} indisponible', catalogTimeout: 'Le catalogue {model} a mis trop de temps à répondre', mapsAvailable: '{available} cartes disponibles sur {total}', hoursAvailable: '{available} heures disponibles sur {total}', mlxSymbol: 'Le symbole MLX identifie les cartes calculées par MeteoLabX.', calculatedBy: 'Calculé par MeteoLabX', mlxDiagnostic: 'Diagnostic calculé par MeteoLabX', noneSelected: 'Aucune carte sélectionnée', valid: 'Valable', downloadPng: 'Télécharger le PNG', downloadMapPng: 'Télécharger la carte en PNG', fullscreen: 'Plein écran', windLevel: 'Niveau vertical du vent', level: 'Niveau', aboveGround: 'Au-dessus du sol', isobaric: 'Isobare', loading: 'Chargement de {product}', downloading: 'Téléchargement de la carte précalculée…', calculating: 'Calcul de {product}', workerPending: 'Le modèle a déjà publié cette heure. MeteoLabX l’ajoutera automatiquement à la fin du traitement.', loadError: 'Impossible de charger la carte réelle', previousHourTry: 'Essayer l’heure précédente', changeUnits: 'Changer les unités', units: 'Unités', previousHour: 'Heure précédente', nextHour: 'Heure suivante', pause: 'Pause', play: 'Lecture', forecastHour: 'Heure prévue', hourAvailable: '{time} UTC disponible', hourPending: '{time} UTC en attente', viewedMap: 'Carte affichée', nativeField: 'Champ {model}', what: 'Ce que représente la carte', interpretation: 'Interprétation', calculation: 'Calcul', sources: 'Documentation', refreshRun: 'Actualiser le RUN', theme: 'Changer de thème', layers: 'Couches de la carte', zoom: 'Commandes de zoom', zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière', resetView: 'Réinitialiser le cadrage', interactiveMap: 'Carte interactive de {product}'
  },
  it: {
    guideUntranslated: 'Questa spiegazione non è ancora tradotta e viene mostrata in spagnolo.', pageTitle: 'Previsione meteo AROME | MeteoLabX', title: 'Previsione numerica', subtitle: 'Mappe dei modelli meteorologici e diagnostica MeteoLabX.', modelConfig: 'Configurazione del modello', model: 'Modello', latestRun: 'Ultima corsa', maps: 'Mappe', selected: 'selezionate', fields: 'campi', diagnostics: 'diagnostica MLX', search: 'Cerca variabile…', searchMap: 'Cerca mappa', mapSelector: 'Selettore mappe', available: 'Disponibile', complete: 'Completa', completed: 'Completo', pending: 'In attesa', connecting: 'Connessione…', backendUnavailable: 'Backend {model} non disponibile', catalogTimeout: 'Il catalogo {model} ha impiegato troppo tempo', mapsAvailable: '{available} mappe disponibili su {total}', hoursAvailable: '{available} ore disponibili su {total}', mlxSymbol: 'Il simbolo MLX identifica le mappe calcolate da MeteoLabX.', calculatedBy: 'Calcolato da MeteoLabX', mlxDiagnostic: 'Diagnostica calcolata da MeteoLabX', noneSelected: 'Nessuna mappa selezionata', valid: 'Valido', downloadPng: 'Scarica PNG', downloadMapPng: 'Scarica la mappa in PNG', fullscreen: 'Schermo intero', windLevel: 'Livello verticale del vento', level: 'Livello', aboveGround: 'Sopra il terreno', isobaric: 'Isobarico', loading: 'Caricamento di {product}', downloading: 'Download della mappa già calcolata…', calculating: 'Calcolo di {product}', workerPending: 'Il modello ha già pubblicato quest’ora. MeteoLabX la aggiungerà automaticamente al termine del worker.', loadError: 'Impossibile caricare la mappa reale', previousHourTry: 'Prova l’ora precedente', changeUnits: 'Cambia unità', units: 'Unità', previousHour: 'Ora precedente', nextHour: 'Ora successiva', pause: 'Pausa', play: 'Riproduci', forecastHour: 'Ora prevista', hourAvailable: '{time} UTC disponibile', hourPending: '{time} UTC in attesa', viewedMap: 'Mappa visualizzata', nativeField: 'Campo {model}', what: 'Cosa rappresenta', interpretation: 'Interpretazione', calculation: 'Calcolo', sources: 'Documentazione', refreshRun: 'Aggiorna RUN', theme: 'Cambia tema', layers: 'Livelli della mappa', zoom: 'Controlli zoom', zoomIn: 'Ingrandisci', zoomOut: 'Riduci', resetView: 'Ripristina inquadratura', interactiveMap: 'Mappa interattiva di {product}'
  },
  pt: {
    guideUntranslated: 'Esta explicação ainda não está traduzida e é apresentada em castelhano.', pageTitle: 'Previsão meteorológica AROME | MeteoLabX', title: 'Previsão numérica', subtitle: 'Mapas de modelos meteorológicos e diagnósticos MeteoLabX.', modelConfig: 'Configuração do modelo', model: 'Modelo', latestRun: 'Última execução', maps: 'Mapas', selected: 'selecionados', fields: 'campos', diagnostics: 'diagnósticos MLX', search: 'Pesquisar variável…', searchMap: 'Pesquisar mapa', mapSelector: 'Seletor de mapas', available: 'Disponível', complete: 'Completa', completed: 'Completo', pending: 'Pendente', connecting: 'A ligar…', backendUnavailable: 'Backend {model} indisponível', catalogTimeout: 'O catálogo de {model} demorou demasiado', mapsAvailable: '{available} de {total} mapas disponíveis', hoursAvailable: '{available} de {total} horas disponíveis', mlxSymbol: 'O símbolo MLX identifica os mapas calculados pelo MeteoLabX.', calculatedBy: 'Calculado pelo MeteoLabX', mlxDiagnostic: 'Diagnóstico calculado pelo MeteoLabX', noneSelected: 'Nenhum mapa selecionado', valid: 'Válido', downloadPng: 'Descarregar PNG', downloadMapPng: 'Descarregar o mapa em PNG', fullscreen: 'Ecrã inteiro', windLevel: 'Nível vertical do vento', level: 'Nível', aboveGround: 'Acima do terreno', isobaric: 'Isobárico', loading: 'A carregar {product}', downloading: 'A descarregar o mapa já calculado…', calculating: 'A calcular {product}', workerPending: 'O modelo já publicou esta hora. O MeteoLabX irá adicioná-la automaticamente quando o worker terminar.', loadError: 'Não foi possível carregar o mapa real', previousHourTry: 'Tentar a hora anterior', changeUnits: 'Alterar unidades', units: 'Unidades', previousHour: 'Hora anterior', nextHour: 'Hora seguinte', pause: 'Pausar', play: 'Reproduzir', forecastHour: 'Hora prevista', hourAvailable: '{time} UTC disponível', hourPending: '{time} UTC pendente', viewedMap: 'Mapa visualizado', nativeField: 'Campo {model}', what: 'O que representa', interpretation: 'Interpretação', calculation: 'Cálculo', sources: 'Documentação', refreshRun: 'Atualizar RUN', theme: 'Alterar tema', layers: 'Camadas do mapa', zoom: 'Controlos de zoom', zoomIn: 'Aproximar', zoomOut: 'Afastar', resetView: 'Repor enquadramento', interactiveMap: 'Mapa interativo de {product}'
  }
};

export function forecastText(language, key, params = {}) {
  let value = (COPY[language] || COPY.es)[key] || COPY.es[key] || key;
  for (const [name, replacement] of Object.entries(params)) value = value.replaceAll(`{${name}}`, replacement);
  return value;
}

export function forecastLocale(language) { return FORECAST_LOCALES[language] || FORECAST_LOCALES.es; }

const CATEGORY_LABELS = {
  ca: ['Temperatura', 'Precipitació', 'Dinàmica atmosfèrica', 'Convecció', 'Humitat', 'Nuvolositat', 'Radiació'],
  en: ['Temperature', 'Precipitation', 'Atmospheric dynamics', 'Convection', 'Humidity', 'Cloud cover', 'Radiation'],
  fr: ['Température', 'Précipitations', 'Dynamique atmosphérique', 'Convection', 'Humidité', 'Nébulosité', 'Rayonnement'],
  it: ['Temperatura', 'Precipitazioni', 'Dinamica atmosferica', 'Convezione', 'Umidità', 'Nuvolosità', 'Radiazione'],
  pt: ['Temperatura', 'Precipitação', 'Dinâmica atmosférica', 'Convecção', 'Humidade', 'Nebulosidade', 'Radiação']
};

const LABEL_REPLACEMENTS = {
  ca: [['y presión al nivel del mar','i pressió al nivell del mar'],['Temperatura de bulbo húmedo','Temperatura de bulb humit'],['Viento por niveles','Vent per nivells'],['Racha máxima horaria','Ratxa màxima horària'],['Cizalladura efectiva','Cisallament efectiu'],['Cizalladura','Cisallament'],['Precipitación acumulada','Precipitació acumulada'],['Precipitación de nieve','Precipitació de neu'],['Precipitación en','Precipitació en'],['Tipo de precipitación','Tipus de precipitació'],['Humedad relativa','Humitat relativa'],['Agua precipitable','Aigua precipitable'],['Altura de la capa límite','Alçada de la capa límit'],['Radiación solar descendente','Radiació solar descendent'],['Radiación solar directa','Radiació solar directa'],['Radiación térmica descendente','Radiació tèrmica descendent'],['Movimiento de células ordinarias','Moviment de cèl·lules ordinàries'],['Inhibición convectiva','Inhibició convectiva'],['Reflectividad simulada','Reflectivitat simulada'],['Densidad de rayos','Densitat de llamps'],['Nubosidad total','Nuvolositat total'],['Nubosidad baja','Nuvolositat baixa'],['Nubosidad alta','Nuvolositat alta'],['Helicidad relativa','Helicitat relativa'],['Velocidad vertical en el NCL','Velocitat vertical al NCL'],['Helicidad de la corriente ascendente','Helicitat del corrent ascendent']],
  en: [['Geopotencial 500 hPa y presión al nivel del mar','500 hPa geopotential and mean sea-level pressure'],['Temperatura y geopotencial','Temperature and geopotential'],['Temperatura a','Temperature at'],['Temperatura de bulbo húmedo','Wet-bulb temperature'],['Viento por niveles','Wind by level'],['Racha máxima horaria','Maximum hourly gust'],['Cizalladura efectiva','Effective bulk wind difference'],['Cizalladura','Wind shear'],['Precipitación acumulada','Accumulated precipitation'],['Precipitación de nieve','Snowfall'],['Precipitación en','Precipitation in'],['Tipo de precipitación','Precipitation type'],['Humedad relativa','Relative humidity'],['Agua precipitable','Precipitable water'],['Altura de la capa límite','Boundary-layer height'],['Radiación solar descendente','Downward solar radiation'],['Radiación solar directa','Direct solar radiation'],['Radiación térmica descendente','Downward thermal radiation'],['Movimiento de células ordinarias','Ordinary cell motion'],['Inhibición convectiva','Convective inhibition'],['Reflectividad simulada','Simulated reflectivity'],['Densidad de rayos','Lightning density'],['Nubosidad total','Total cloud cover'],['Nubosidad baja','Low cloud cover'],['Nubosidad alta','High cloud cover'],['y presión al nivel del mar','and mean sea-level pressure'],['Helicidad relativa','Storm-relative helicity'],['Velocidad vertical en el NCL','Vertical velocity at the LFC'],['Helicidad de la corriente ascendente','Updraft helicity']],
  fr: [['y presión al nivel del mar','et pression au niveau de la mer'],['Temperatura y geopotencial','Température et géopotentiel'],['Temperatura a','Température à'],['Temperatura de bulbo húmedo','Température du thermomètre mouillé'],['Viento por niveles','Vent par niveau'],['Racha máxima horaria','Rafale horaire maximale'],['Cizalladura efectiva','Cisaillement effectif'],['Cizalladura','Cisaillement'],['Precipitación acumulada','Précipitations cumulées'],['Precipitación de nieve','Précipitations neigeuses'],['Precipitación en','Précipitations en'],['Tipo de precipitación','Type de précipitations'],['Humedad relativa','Humidité relative'],['Agua precipitable','Eau précipitable'],['Altura de la capa límite','Hauteur de la couche limite'],['Radiación solar descendente','Rayonnement solaire descendant'],['Radiación solar directa','Rayonnement solaire direct'],['Radiación térmica descendente','Rayonnement thermique descendant'],['Movimiento de células ordinarias','Déplacement des cellules ordinaires'],['Inhibición convectiva','Inhibition convective'],['Reflectividad simulada','Réflectivité simulée'],['Densidad de rayos','Densité de foudre'],['Nubosidad total','Nébulosité totale'],['Nubosidad baja','Nébulosité basse'],['Nubosidad alta','Nébulosité élevée'],['Helicidad relativa','Hélicité relative'],['Velocidad vertical en el NCL','Vitesse verticale au NCL'],['Helicidad de la corriente ascendente','Hélicité du courant ascendant']],
  it: [['y presión al nivel del mar','e pressione al livello del mare'],['Temperatura y geopotencial','Temperatura e geopotenziale'],['Temperatura a','Temperatura a'],['Temperatura de bulbo húmedo','Temperatura di bulbo umido'],['Viento por niveles','Vento per livelli'],['Racha máxima horaria','Raffica oraria massima'],['Cizalladura efectiva','Shear effettivo'],['Cizalladura','Wind shear'],['Precipitación acumulada','Precipitazione accumulata'],['Precipitación de nieve','Precipitazione nevosa'],['Precipitación en','Precipitazione in'],['Tipo de precipitación','Tipo di precipitazione'],['Humedad relativa','Umidità relativa'],['Agua precipitable','Acqua precipitabile'],['Altura de la capa límite','Altezza dello strato limite'],['Radiación solar descendente','Radiazione solare discendente'],['Radiación solar directa','Radiazione solare diretta'],['Radiación térmica descendente','Radiazione termica discendente'],['Movimiento de células ordinarias','Moto delle celle ordinarie'],['Inhibición convectiva','Inibizione convettiva'],['Reflectividad simulada','Riflettività simulata'],['Densidad de rayos','Densità dei fulmini'],['Nubosidad total','Nuvolosità totale'],['Nubosidad baja','Nuvolosità bassa'],['Nubosidad alta','Nuvolosità alta'],['Helicidad relativa','Elicità relativa'],['Velocidad vertical en el NCL','Velocità verticale al NCL'],['Helicidad de la corriente ascendente','Elicità della corrente ascendente']],
  pt: [['y presión al nivel del mar','e pressão ao nível do mar'],['Temperatura y geopotencial','Temperatura e geopotencial'],['Temperatura a','Temperatura a'],['Temperatura de bulbo húmedo','Temperatura de bolbo húmido'],['Viento por niveles','Vento por níveis'],['Racha máxima horaria','Rajada horária máxima'],['Cizalladura efectiva','Cisalhamento efetivo'],['Cizalladura','Cisalhamento'],['Precipitación acumulada','Precipitação acumulada'],['Precipitación de nieve','Precipitação de neve'],['Precipitación en','Precipitação em'],['Tipo de precipitación','Tipo de precipitação'],['Humedad relativa','Humidade relativa'],['Agua precipitable','Água precipitável'],['Altura de la capa límite','Altura da camada limite'],['Radiación solar descendente','Radiação solar descendente'],['Radiación solar directa','Radiação solar direta'],['Radiación térmica descendente','Radiação térmica descendente'],['Movimiento de células ordinarias','Movimento de células comuns'],['Inhibición convectiva','Inibição convectiva'],['Reflectividad simulada','Refletividade simulada'],['Densidad de rayos','Densidade de raios'],['Nubosidad total','Nebulosidade total'],['Nubosidad baja','Nebulosidade baixa'],['Nubosidad alta','Nebulosidade alta'],['Helicidad relativa','Helicidade relativa'],['Velocidad vertical en el NCL','Velocidade vertical no NCL'],['Helicidad de la corriente ascendente','Helicidade da corrente ascendente']]
};

export function localizedForecastCategories(categories, language) {
  const labels = CATEGORY_LABELS[language];
  return labels ? categories.map((item, index) => ({ ...item, label: labels[index] })) : categories;
}

export function localizedForecastProducts(products, language) {
  const replacements = LABEL_REPLACEMENTS[language];
  if (!replacements) return products;
  return products.map((item) => ({
    ...item,
    label: replacements.reduce((text, [from, to]) => text.replace(from, to), item.label),
    contents: item.contents
      ? replacements.reduce((text, [from, to]) => text.replace(from, to), item.contents)
      : item.contents
  }));
}

const LAYER_LABELS = {
  es: { isotherms: 'Isotermas', isohypses: 'Isohipsas', troughs: 'Ejes de vaguada', centres: 'Centros de presión' },
  ca: { isotherms: 'Isotermes', isohypses: 'Isohipses', troughs: 'Eixos de vaguada', centres: 'Centres de pressió' },
  en: { isotherms: 'Isotherms', isohypses: 'Height contours', troughs: 'Trough axes', centres: 'Pressure centres' },
  fr: { isotherms: 'Isothermes', isohypses: 'Isohypses', troughs: 'Axes de thalweg', centres: 'Centres de pression' },
  it: { isotherms: 'Isoterme', isohypses: 'Isoipse', troughs: 'Assi di saccatura', centres: 'Centri di pressione' },
  pt: { isotherms: 'Isotérmicas', isohypses: 'Isoípsas', troughs: 'Eixos de cavado', centres: 'Centros de pressão' }
};

export function forecastLayerLabel(language, id, fallback) {
  return (LAYER_LABELS[language] || LAYER_LABELS.es)[id] || fallback;
}
