export const FORECAST_LOCALES = {
  es: 'es-ES', ca: 'ca-ES', en: 'en-GB', de: 'de-DE', fr: 'fr-FR', it: 'it-IT', pt: 'pt-PT'
};

const COPY = {
  es: {
    guideUntranslated: 'Explicación disponible en castellano.', pageTitle: 'Predicción meteorológica | MeteoLabX', title: 'Predicción numérica', subtitle: 'Mapas de modelos meteorológicos y diagnósticos de MeteoLabX.', modelConfig: 'Configuración del modelo', model: 'Modelo', domain: 'Dominio', latestRun: 'Última pasada', maps: 'Mapas', availableMaps: 'disponibles', fields: 'campos', diagnostics: 'diagnósticos MLX', search: 'Buscar variable…', searchMap: 'Buscar mapa', mapSelector: 'Selector de mapas', available: 'Disponible', complete: 'Completa', completed: 'Completo', pending: 'Pendiente', connecting: 'Conectando…', backendUnavailable: 'Backend {model} no disponible', catalogTimeout: 'El catálogo de {model} ha tardado demasiado', mapsAvailable: '{available} de {total} mapas disponibles', hoursAvailable: '{available} de {total} horas disponibles', mlxSymbol: 'El símbolo MLX identifica los mapas calculados por MeteoLabX.', calculatedBy: 'Calculado por MeteoLabX', mlxDiagnostic: 'Diagnóstico calculado por MeteoLabX', noneSelected: 'Ningún mapa seleccionado', valid: 'Válido', downloadPng: 'Descargar PNG', downloadMapPng: 'Descargar el mapa en PNG', downloadGif: 'Descargar GIF', downloadMapGif: 'Animación GIF', gifFrom: 'Desde', gifTo: 'Hasta', gifFrames: '{count} horas', gifCreate: 'Crear GIF', gifCancel: 'Cancelar el GIF', gifEmpty: 'Ninguna de esas horas se ha podido cargar.', fullscreen: 'Pantalla completa', exitFullscreen: 'Salir de pantalla completa', windLevel: 'Nivel vertical del viento', level: 'Nivel', aboveGround: 'Sobre terreno', isobaric: 'Isobárico', loading: 'Cargando {product}', downloading: 'Descargando el mapa ya calculado…', calculating: 'Calculando {product}', workerPending: 'El modelo ya ha publicado esta hora. MeteoLabX la añadirá automáticamente al terminar el worker.', loadError: 'No se pudo cargar el mapa real', previousHourTry: 'Probar la hora anterior', changeUnits: 'Cambiar unidades', units: 'Unidades', previousHour: 'Hora anterior', nextHour: 'Hora siguiente', pause: 'Pausar', play: 'Reproducir', forecastHour: 'Hora prevista', hourAvailable: '{time} UTC disponible', hourPending: '{time} UTC pendiente', viewedMap: 'Mapa visualizado', nativeField: 'Campo {model}', what: 'Qué representa', interpretation: 'Interpretación', calculation: 'Cálculo', sources: 'Base documental', theme: 'Cambiar tema', layers: 'Capas del mapa', zoom: 'Controles de zoom', zoomIn: 'Acercar mapa', zoomOut: 'Alejar mapa', resetView: 'Restablecer encuadre', movingWindow: 'ventana móvil', windowStart: 'Inicio de la ventana', windowEnd: 'Fin de la ventana', windowAccumulated: 'Acumulado', interactiveMap: 'Mapa interactivo de {product}'
  },
  ca: {
    guideUntranslated: 'Aquesta explicació encara no està traduïda i es mostra en castellà.', pageTitle: 'Predicció meteorològica | MeteoLabX', title: 'Predicció numèrica', subtitle: 'Mapes de models meteorològics i diagnòstics de MeteoLabX.', modelConfig: 'Configuració del model', model: 'Model', domain: 'Domini', latestRun: 'Darrera passada', maps: 'Mapes', availableMaps: 'disponibles', fields: 'camps', diagnostics: 'diagnòstics MLX', search: 'Cerca una variable…', searchMap: 'Cerca un mapa', mapSelector: 'Selector de mapes', available: 'Disponible', complete: 'Completa', completed: 'Complet', pending: 'Pendent', connecting: 'Connectant…', backendUnavailable: 'Backend {model} no disponible', catalogTimeout: 'El catàleg de {model} ha trigat massa', mapsAvailable: '{available} de {total} mapes disponibles', hoursAvailable: '{available} de {total} hores disponibles', mlxSymbol: 'El símbol MLX identifica els mapes calculats per MeteoLabX.', calculatedBy: 'Calculat per MeteoLabX', mlxDiagnostic: 'Diagnòstic calculat per MeteoLabX', noneSelected: 'Cap mapa seleccionat', valid: 'Vàlid', downloadPng: 'Descarrega PNG', downloadMapPng: 'Descarrega el mapa en PNG', downloadGif: 'Descarrega GIF', downloadMapGif: 'Animació GIF', gifFrom: 'Des de', gifTo: 'Fins a', gifFrames: '{count} hores', gifCreate: 'Crea el GIF', gifCancel: 'Cancel·la el GIF', gifEmpty: 'No s’ha pogut carregar cap d’aquestes hores.', fullscreen: 'Pantalla completa', exitFullscreen: 'Surt de la pantalla completa', windLevel: 'Nivell vertical del vent', level: 'Nivell', aboveGround: 'Sobre el terreny', isobaric: 'Isobàric', loading: 'Carregant {product}', downloading: 'Descarregant el mapa ja calculat…', calculating: 'Calculant {product}', workerPending: 'El model ja ha publicat aquesta hora. MeteoLabX l’afegirà automàticament quan acabi el worker.', loadError: 'No s’ha pogut carregar el mapa real', previousHourTry: 'Prova l’hora anterior', changeUnits: 'Canvia les unitats', units: 'Unitats', previousHour: 'Hora anterior', nextHour: 'Hora següent', pause: 'Pausa', play: 'Reprodueix', forecastHour: 'Hora prevista', hourAvailable: '{time} UTC disponible', hourPending: '{time} UTC pendent', viewedMap: 'Mapa visualitzat', nativeField: 'Camp {model}', what: 'Què representa', interpretation: 'Interpretació', calculation: 'Càlcul', sources: 'Base documental', theme: 'Canvia el tema', layers: 'Capes del mapa', zoom: 'Controls de zoom', zoomIn: 'Apropa el mapa', zoomOut: 'Allunya el mapa', resetView: 'Restableix l’enquadrament', movingWindow: 'finestra mòbil', windowStart: 'Inici de la finestra', windowEnd: 'Final de la finestra', windowAccumulated: 'Acumulat', interactiveMap: 'Mapa interactiu de {product}'
  },
  en: {
    guideUntranslated: 'This explanation has not been translated yet and is shown in Spanish.', pageTitle: 'Weather forecast | MeteoLabX', title: 'Numerical forecast', subtitle: 'Weather-model maps and MeteoLabX diagnostics.', modelConfig: 'Model settings', model: 'Model', domain: 'Domain', latestRun: 'Latest run', maps: 'Maps', availableMaps: 'available', fields: 'fields', diagnostics: 'MLX diagnostics', search: 'Search variable…', searchMap: 'Search map', mapSelector: 'Map selector', available: 'Available', complete: 'Complete', completed: 'Complete', pending: 'Pending', connecting: 'Connecting…', backendUnavailable: '{model} backend unavailable', catalogTimeout: 'The {model} catalogue took too long to respond', mapsAvailable: '{available} of {total} maps available', hoursAvailable: '{available} of {total} hours available', mlxSymbol: 'The MLX symbol identifies maps calculated by MeteoLabX.', calculatedBy: 'Calculated by MeteoLabX', mlxDiagnostic: 'Diagnostic calculated by MeteoLabX', noneSelected: 'No map selected', valid: 'Valid', downloadPng: 'Download PNG', downloadMapPng: 'Download map as PNG', downloadGif: 'Download GIF', downloadMapGif: 'GIF animation', gifFrom: 'From', gifTo: 'To', gifFrames: '{count} hours', gifCreate: 'Create GIF', gifCancel: 'Cancel GIF', gifEmpty: 'None of those hours could be loaded.', fullscreen: 'Full screen', exitFullscreen: 'Exit full screen', windLevel: 'Wind vertical level', level: 'Level', aboveGround: 'Above ground', isobaric: 'Isobaric', loading: 'Loading {product}', downloading: 'Downloading the precomputed map…', calculating: 'Calculating {product}', workerPending: 'The model has published this hour. MeteoLabX will add it automatically when the worker finishes.', loadError: 'The live map could not be loaded', previousHourTry: 'Try the previous hour', changeUnits: 'Change units', units: 'Units', previousHour: 'Previous hour', nextHour: 'Next hour', pause: 'Pause', play: 'Play', forecastHour: 'Forecast hour', hourAvailable: '{time} UTC available', hourPending: '{time} UTC pending', viewedMap: 'Map shown', nativeField: '{model} field', what: 'What it shows', interpretation: 'Interpretation', calculation: 'Calculation', sources: 'References', theme: 'Change theme', layers: 'Map layers', zoom: 'Zoom controls', zoomIn: 'Zoom in', zoomOut: 'Zoom out', resetView: 'Reset view', movingWindow: 'moving window', windowStart: 'Window start', windowEnd: 'Window end', windowAccumulated: 'Accumulated', interactiveMap: 'Interactive map of {product}'
  },
  de: {
    guideUntranslated: 'Diese Erläuterung ist noch nicht übersetzt und wird auf Spanisch angezeigt.', pageTitle: 'Wettervorhersage | MeteoLabX', title: 'Numerische Vorhersage', subtitle: 'Wettermodellkarten und MeteoLabX-Diagnosen.', modelConfig: 'Modelleinstellungen', model: 'Modell', domain: 'Gebiet', latestRun: 'Neuester Lauf', maps: 'Karten', availableMaps: 'verfügbar', fields: 'Felder', diagnostics: 'MLX-Diagnosen', search: 'Variable suchen…', searchMap: 'Karte suchen', mapSelector: 'Kartenauswahl', available: 'Verfügbar', complete: 'Vollständig', completed: 'Abgeschlossen', pending: 'Ausstehend', connecting: 'Verbindung wird hergestellt…', backendUnavailable: '{model}-Backend nicht verfügbar', catalogTimeout: 'Der {model}-Katalog hat nicht rechtzeitig geantwortet', mapsAvailable: '{available} von {total} Karten verfügbar', hoursAvailable: '{available} von {total} Stunden verfügbar', mlxSymbol: 'Das MLX-Symbol kennzeichnet von MeteoLabX berechnete Karten.', calculatedBy: 'Von MeteoLabX berechnet', mlxDiagnostic: 'Von MeteoLabX berechnete Diagnose', noneSelected: 'Keine Karte ausgewählt', valid: 'Gültig', downloadPng: 'PNG herunterladen', downloadMapPng: 'Karte als PNG herunterladen', downloadGif: 'GIF herunterladen', downloadMapGif: 'GIF-Animation', gifFrom: 'Von', gifTo: 'Bis', gifFrames: '{count} Stunden', gifCreate: 'GIF erstellen', gifCancel: 'GIF abbrechen', gifEmpty: 'Keine dieser Stunden konnte geladen werden.', fullscreen: 'Vollbild', exitFullscreen: 'Vollbild beenden', windLevel: 'Vertikale Windebene', level: 'Ebene', aboveGround: 'Über Grund', isobaric: 'Isobarisch', loading: '{product} wird geladen', downloading: 'Vorberechnete Karte wird heruntergeladen…', calculating: '{product} wird berechnet', workerPending: 'Das Modell hat diese Stunde veröffentlicht. MeteoLabX fügt sie nach Abschluss des Workers automatisch hinzu.', loadError: 'Die aktuelle Karte konnte nicht geladen werden', previousHourTry: 'Vorherige Stunde versuchen', changeUnits: 'Einheiten ändern', units: 'Einheiten', previousHour: 'Vorherige Stunde', nextHour: 'Nächste Stunde', pause: 'Pause', play: 'Wiedergabe', forecastHour: 'Vorhersagestunde', hourAvailable: '{time} UTC verfügbar', hourPending: '{time} UTC ausstehend', viewedMap: 'Angezeigte Karte', nativeField: '{model}-Feld', what: 'Darstellung', interpretation: 'Interpretation', calculation: 'Berechnung', sources: 'Quellen', theme: 'Design ändern', layers: 'Kartenebenen', zoom: 'Zoomsteuerung', zoomIn: 'Vergrößern', zoomOut: 'Verkleinern', resetView: 'Ansicht zurücksetzen', movingWindow: 'gleitendes Fenster', windowStart: 'Fensteranfang', windowEnd: 'Fensterende', windowAccumulated: 'Summe', interactiveMap: 'Interaktive Karte: {product}'
  },
  fr: {
    guideUntranslated: 'Cette explication n’est pas encore traduite et s’affiche en espagnol.', pageTitle: 'Prévision météo | MeteoLabX', title: 'Prévision numérique', subtitle: 'Cartes de modèles météorologiques et diagnostics MeteoLabX.', modelConfig: 'Configuration du modèle', model: 'Modèle', domain: 'Domaine', latestRun: 'Dernier run', maps: 'Cartes', availableMaps: 'disponibles', fields: 'champs', diagnostics: 'diagnostics MLX', search: 'Rechercher une variable…', searchMap: 'Rechercher une carte', mapSelector: 'Sélecteur de cartes', available: 'Disponible', complete: 'Complet', completed: 'Complet', pending: 'En attente', connecting: 'Connexion…', backendUnavailable: 'Backend {model} indisponible', catalogTimeout: 'Le catalogue {model} a mis trop de temps à répondre', mapsAvailable: '{available} cartes disponibles sur {total}', hoursAvailable: '{available} heures disponibles sur {total}', mlxSymbol: 'Le symbole MLX identifie les cartes calculées par MeteoLabX.', calculatedBy: 'Calculé par MeteoLabX', mlxDiagnostic: 'Diagnostic calculé par MeteoLabX', noneSelected: 'Aucune carte sélectionnée', valid: 'Valable', downloadPng: 'Télécharger le PNG', downloadMapPng: 'Télécharger la carte en PNG', downloadGif: 'Télécharger le GIF', downloadMapGif: 'Animation GIF', gifFrom: 'De', gifTo: 'À', gifFrames: '{count} heures', gifCreate: 'Créer le GIF', gifCancel: 'Annuler le GIF', gifEmpty: 'Aucune de ces heures n’a pu être chargée.', fullscreen: 'Plein écran', exitFullscreen: 'Quitter le plein écran', windLevel: 'Niveau vertical du vent', level: 'Niveau', aboveGround: 'Au-dessus du sol', isobaric: 'Isobare', loading: 'Chargement de {product}', downloading: 'Téléchargement de la carte précalculée…', calculating: 'Calcul de {product}', workerPending: 'Le modèle a déjà publié cette heure. MeteoLabX l’ajoutera automatiquement à la fin du traitement.', loadError: 'Impossible de charger la carte réelle', previousHourTry: 'Essayer l’heure précédente', changeUnits: 'Changer les unités', units: 'Unités', previousHour: 'Heure précédente', nextHour: 'Heure suivante', pause: 'Pause', play: 'Lecture', forecastHour: 'Heure prévue', hourAvailable: '{time} UTC disponible', hourPending: '{time} UTC en attente', viewedMap: 'Carte affichée', nativeField: 'Champ {model}', what: 'Ce que représente la carte', interpretation: 'Interprétation', calculation: 'Calcul', sources: 'Documentation', theme: 'Changer de thème', layers: 'Couches de la carte', zoom: 'Commandes de zoom', zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière', resetView: 'Réinitialiser le cadrage', movingWindow: 'fenêtre glissante', windowStart: 'Début de la fenêtre', windowEnd: 'Fin de la fenêtre', windowAccumulated: 'Cumul', interactiveMap: 'Carte interactive de {product}'
  },
  it: {
    guideUntranslated: 'Questa spiegazione non è ancora tradotta e viene mostrata in spagnolo.', pageTitle: 'Previsione meteo | MeteoLabX', title: 'Previsione numerica', subtitle: 'Mappe dei modelli meteorologici e diagnostica MeteoLabX.', modelConfig: 'Configurazione del modello', model: 'Modello', domain: 'Dominio', latestRun: 'Ultima corsa', maps: 'Mappe', availableMaps: 'disponibili', fields: 'campi', diagnostics: 'diagnostica MLX', search: 'Cerca variabile…', searchMap: 'Cerca mappa', mapSelector: 'Selettore mappe', available: 'Disponibile', complete: 'Completa', completed: 'Completo', pending: 'In attesa', connecting: 'Connessione…', backendUnavailable: 'Backend {model} non disponibile', catalogTimeout: 'Il catalogo {model} ha impiegato troppo tempo', mapsAvailable: '{available} mappe disponibili su {total}', hoursAvailable: '{available} ore disponibili su {total}', mlxSymbol: 'Il simbolo MLX identifica le mappe calcolate da MeteoLabX.', calculatedBy: 'Calcolato da MeteoLabX', mlxDiagnostic: 'Diagnostica calcolata da MeteoLabX', noneSelected: 'Nessuna mappa selezionata', valid: 'Valido', downloadPng: 'Scarica PNG', downloadMapPng: 'Scarica la mappa in PNG', downloadGif: 'Scarica GIF', downloadMapGif: 'Animazione GIF', gifFrom: 'Da', gifTo: 'A', gifFrames: '{count} ore', gifCreate: 'Crea GIF', gifCancel: 'Annulla GIF', gifEmpty: 'Nessuna di queste ore è stata caricata.', fullscreen: 'Schermo intero', exitFullscreen: 'Esci da schermo intero', windLevel: 'Livello verticale del vento', level: 'Livello', aboveGround: 'Sopra il terreno', isobaric: 'Isobarico', loading: 'Caricamento di {product}', downloading: 'Download della mappa già calcolata…', calculating: 'Calcolo di {product}', workerPending: 'Il modello ha già pubblicato quest’ora. MeteoLabX la aggiungerà automaticamente al termine del worker.', loadError: 'Impossibile caricare la mappa reale', previousHourTry: 'Prova l’ora precedente', changeUnits: 'Cambia unità', units: 'Unità', previousHour: 'Ora precedente', nextHour: 'Ora successiva', pause: 'Pausa', play: 'Riproduci', forecastHour: 'Ora prevista', hourAvailable: '{time} UTC disponibile', hourPending: '{time} UTC in attesa', viewedMap: 'Mappa visualizzata', nativeField: 'Campo {model}', what: 'Cosa rappresenta', interpretation: 'Interpretazione', calculation: 'Calcolo', sources: 'Documentazione', theme: 'Cambia tema', layers: 'Livelli della mappa', zoom: 'Controlli zoom', zoomIn: 'Ingrandisci', zoomOut: 'Riduci', resetView: 'Ripristina inquadratura', movingWindow: 'finestra mobile', windowStart: 'Inizio della finestra', windowEnd: 'Fine della finestra', windowAccumulated: 'Cumulata', interactiveMap: 'Mappa interattiva di {product}'
  },
  pt: {
    guideUntranslated: 'Esta explicação ainda não está traduzida e é apresentada em castelhano.', pageTitle: 'Previsão meteorológica | MeteoLabX', title: 'Previsão numérica', subtitle: 'Mapas de modelos meteorológicos e diagnósticos MeteoLabX.', modelConfig: 'Configuração do modelo', model: 'Modelo', domain: 'Domínio', latestRun: 'Última execução', maps: 'Mapas', availableMaps: 'disponíveis', fields: 'campos', diagnostics: 'diagnósticos MLX', search: 'Pesquisar variável…', searchMap: 'Pesquisar mapa', mapSelector: 'Seletor de mapas', available: 'Disponível', complete: 'Completa', completed: 'Completo', pending: 'Pendente', connecting: 'A ligar…', backendUnavailable: 'Backend {model} indisponível', catalogTimeout: 'O catálogo de {model} demorou demasiado', mapsAvailable: '{available} de {total} mapas disponíveis', hoursAvailable: '{available} de {total} horas disponíveis', mlxSymbol: 'O símbolo MLX identifica os mapas calculados pelo MeteoLabX.', calculatedBy: 'Calculado pelo MeteoLabX', mlxDiagnostic: 'Diagnóstico calculado pelo MeteoLabX', noneSelected: 'Nenhum mapa selecionado', valid: 'Válido', downloadPng: 'Descarregar PNG', downloadMapPng: 'Descarregar o mapa em PNG', downloadGif: 'Descarregar GIF', downloadMapGif: 'Animação GIF', gifFrom: 'De', gifTo: 'Até', gifFrames: '{count} horas', gifCreate: 'Criar GIF', gifCancel: 'Cancelar o GIF', gifEmpty: 'Nenhuma dessas horas pôde ser carregada.', fullscreen: 'Ecrã inteiro', exitFullscreen: 'Sair do ecrã inteiro', windLevel: 'Nível vertical do vento', level: 'Nível', aboveGround: 'Acima do terreno', isobaric: 'Isobárico', loading: 'A carregar {product}', downloading: 'A descarregar o mapa já calculado…', calculating: 'A calcular {product}', workerPending: 'O modelo já publicou esta hora. O MeteoLabX irá adicioná-la automaticamente quando o worker terminar.', loadError: 'Não foi possível carregar o mapa real', previousHourTry: 'Tentar a hora anterior', changeUnits: 'Alterar unidades', units: 'Unidades', previousHour: 'Hora anterior', nextHour: 'Hora seguinte', pause: 'Pausar', play: 'Reproduzir', forecastHour: 'Hora prevista', hourAvailable: '{time} UTC disponível', hourPending: '{time} UTC pendente', viewedMap: 'Mapa visualizado', nativeField: 'Campo {model}', what: 'O que representa', interpretation: 'Interpretação', calculation: 'Cálculo', sources: 'Documentação', theme: 'Alterar tema', layers: 'Camadas do mapa', zoom: 'Controlos de zoom', zoomIn: 'Aproximar', zoomOut: 'Afastar', resetView: 'Repor enquadramento', movingWindow: 'janela móvel', windowStart: 'Início da janela', windowEnd: 'Fim da janela', windowAccumulated: 'Acumulado', interactiveMap: 'Mapa interativo de {product}'
  }
};

export function forecastText(language, key, params = {}) {
  let value = (COPY[language] || COPY.es)[key] || COPY.es[key] || key;
  for (const [name, replacement] of Object.entries(params)) value = value.replaceAll(`{${name}}`, replacement);
  return value;
}

export function forecastLocale(language) { return FORECAST_LOCALES[language] || FORECAST_LOCALES.es; }

const CATEGORY_LABELS = {
  ca: ['Temperatura', 'Precipitació', 'Vent i dinàmica', 'Inestabilitat', 'Cisallament i helicitat', 'Forçament i cinemàtica', 'Temps sever', 'Núvols i humitat', 'Ciclogènesi extratropical', 'Ciclogènesi tropical'],
  en: ['Temperature', 'Precipitation', 'Wind and dynamics', 'Instability', 'Shear and helicity', 'Forcing and kinematics', 'Severe weather', 'Clouds and humidity', 'Extratropical cyclogenesis', 'Tropical cyclogenesis'],
  de: ['Temperatur', 'Niederschlag', 'Wind und Dynamik', 'Labilität', 'Scherung und Helizität', 'Antrieb und Kinematik', 'Unwetter', 'Wolken und Feuchte', 'Außertropische Zyklogenese', 'Tropische Zyklogenese'],
  fr: ['Température', 'Précipitations', 'Vent et dynamique', 'Instabilité', 'Cisaillement et hélicité', 'Forçage et cinématique', 'Temps violent', 'Nuages et humidité', 'Cyclogenèse extratropicale', 'Cyclogenèse tropicale'],
  it: ['Temperatura', 'Precipitazioni', 'Vento e dinamica', 'Instabilità', 'Wind shear ed elicità', 'Forzanti e cinematica', 'Fenomeni severi', 'Nubi e umidità', 'Ciclogenesi extratropicale', 'Ciclogenesi tropicale'],
  pt: ['Temperatura', 'Precipitação', 'Vento e dinâmica', 'Instabilidade', 'Cisalhamento e helicidade', 'Forçamento e cinemática', 'Tempo severo', 'Nuvens e humidade', 'Ciclogénese extratropical', 'Ciclogénese tropical']
};

const LABEL_REPLACEMENTS = {
  ca: [['Vorticidad absoluta a 850 hPa','Vorticitat absoluta a 850 hPa'],['Vorticidad absoluta · Presión','Vorticitat absoluta · Pressió'],['Intensidad potencial máxima (MPI)','Intensitat potencial màxima (MPI)'],['Intensidad potencial · Presión','Intensitat potencial · Pressió'],['Índice de potencial de génesis (GPI)','Índex de potencial de gènesi (GPI)'],['Potencial de génesis · Presión','Potencial de gènesi · Pressió'],['y presión al nivel del mar','i pressió al nivell del mar'],['Temperatura de bulbo húmedo','Temperatura de bulb humit'],['Viento por niveles','Vent per nivells'],['Racha máxima horaria','Ratxa màxima horària'],['Cizalladura efectiva','Cisallament efectiu'],['Cizalladura','Cisallament'],['Precipitación acumulada','Precipitació acumulada'],['Precipitación de nieve','Precipitació de neu'],['Precipitación en','Precipitació en'],['Tipo de precipitación','Tipus de precipitació'],['Humedad relativa','Humitat relativa'],['Agua precipitable','Aigua precipitable'],['Altura de la capa límite','Alçada de la capa límit'],['Radiación solar descendente','Radiació solar descendent'],['Radiación solar directa','Radiació solar directa'],['Radiación térmica descendente','Radiació tèrmica descendent'],['Movimiento de células ordinarias','Moviment de cèl·lules ordinàries'],['Inhibición convectiva','Inhibició convectiva'],['Reflectividad simulada','Reflectivitat simulada'],['Densidad de rayos','Densitat de llamps'],['Nubosidad total','Nuvolositat total'],['Nubosidad baja','Nuvolositat baixa'],['Nubosidad alta','Nuvolositat alta'],['Helicidad relativa','Helicitat relativa'],['Velocidad vertical en el NCL','Velocitat vertical al NCL'],['Helicidad de la corriente ascendente','Helicitat del corrent ascendent']],
  en: [['Vorticidad absoluta a 850 hPa','Absolute vorticity at 850 hPa'],['Vorticidad absoluta · Presión','Absolute vorticity · Pressure'],['Intensidad potencial máxima (MPI)','Maximum potential intensity (MPI)'],['Intensidad potencial · Presión','Potential intensity · Pressure'],['Índice de potencial de génesis (GPI)','Genesis potential index (GPI)'],['Potencial de génesis · Presión','Genesis potential · Pressure'],['Geopotencial 500 hPa y presión al nivel del mar','500 hPa geopotential and mean sea-level pressure'],['Temperatura y geopotencial','Temperature and geopotential'],['Temperatura a','Temperature at'],['Temperatura de bulbo húmedo','Wet-bulb temperature'],['Viento por niveles','Wind by level'],['Racha máxima horaria','Maximum hourly gust'],['Cizalladura efectiva','Effective bulk wind difference'],['Cizalladura','Wind shear'],['Precipitación acumulada','Accumulated precipitation'],['Precipitación de nieve','Snowfall'],['Precipitación en','Precipitation in'],['Tipo de precipitación','Precipitation type'],['Humedad relativa','Relative humidity'],['Agua precipitable','Precipitable water'],['Altura de la capa límite','Boundary-layer height'],['Radiación solar descendente','Downward solar radiation'],['Radiación solar directa','Direct solar radiation'],['Radiación térmica descendente','Downward thermal radiation'],['Movimiento de células ordinarias','Ordinary cell motion'],['Inhibición convectiva','Convective inhibition'],['Reflectividad simulada','Simulated reflectivity'],['Densidad de rayos','Lightning density'],['Nubosidad total','Total cloud cover'],['Nubosidad baja','Low cloud cover'],['Nubosidad alta','High cloud cover'],['y presión al nivel del mar','and mean sea-level pressure'],['Helicidad relativa','Storm-relative helicity'],['Velocidad vertical en el NCL','Vertical velocity at the LFC'],['Helicidad de la corriente ascendente','Updraft helicity']],
  de: [['Vorticidad absoluta a 850 hPa','Absolute Vorticity in 850 hPa'],['Vorticidad absoluta · Presión','Absolute Vorticity · Luftdruck'],['Intensidad potencial máxima (MPI)','Maximale potenzielle Intensität (MPI)'],['Intensidad potencial · Presión','Potenzielle Intensität · Luftdruck'],['Índice de potencial de génesis (GPI)','Genesepotenzialindex (GPI)'],['Potencial de génesis · Presión','Genesepotenzial · Luftdruck'],['Geopotencial 500 hPa y presión al nivel del mar','Geopotenzial 500 hPa und Luftdruck auf Meereshöhe'],['Temperatura y geopotencial','Temperatur und Geopotenzial'],['Temperatura a','Temperatur auf'],['Temperatura de bulbo húmedo','Feuchttemperatur'],['Viento por niveles','Wind nach Höhenebene'],['Racha máxima horaria','Maximale stündliche Böe'],['Cizalladura efectiva','Effektive Windscherung'],['Cizalladura','Windscherung'],['Precipitación acumulada','Akkumulierter Niederschlag'],['Precipitación de nieve','Schneefall'],['Precipitación en','Niederschlag in'],['Tipo de precipitación','Niederschlagsart'],['Humedad relativa','Relative Luftfeuchte'],['Agua precipitable','Niederschlagbares Wasser'],['Altura de la capa límite','Grenzschichthöhe'],['Radiación solar descendente','Abwärtsgerichtete Solarstrahlung'],['Radiación solar directa','Direkte Solarstrahlung'],['Radiación térmica descendente','Abwärtsgerichtete Wärmestrahlung'],['Inhibición convectiva','Konvektionshemmung'],['Reflectividad simulada','Simulierte Reflektivität'],['Densidad de rayos','Blitzdichte'],['Nubosidad total','Gesamtbewölkung'],['Nubosidad baja','Tiefe Bewölkung'],['Nubosidad alta','Hohe Bewölkung'],['y presión al nivel del mar','und Luftdruck auf Meereshöhe'],['Helicidad relativa','Sturmrelative Helizität']],
  fr: [['Vorticidad absoluta a 850 hPa','Tourbillon absolu à 850 hPa'],['Vorticidad absoluta · Presión','Tourbillon absolu · Pression'],['Intensidad potencial máxima (MPI)','Intensité potentielle maximale (MPI)'],['Intensidad potencial · Presión','Intensité potentielle · Pression'],['Índice de potencial de génesis (GPI)','Indice de potentiel de cyclogenèse (GPI)'],['Potencial de génesis · Presión','Potentiel de cyclogenèse · Pression'],['y presión al nivel del mar','et pression au niveau de la mer'],['Temperatura y geopotencial','Température et géopotentiel'],['Temperatura a','Température à'],['Temperatura de bulbo húmedo','Température du thermomètre mouillé'],['Viento por niveles','Vent par niveau'],['Racha máxima horaria','Rafale horaire maximale'],['Cizalladura efectiva','Cisaillement effectif'],['Cizalladura','Cisaillement'],['Precipitación acumulada','Précipitations cumulées'],['Precipitación de nieve','Précipitations neigeuses'],['Precipitación en','Précipitations en'],['Tipo de precipitación','Type de précipitations'],['Humedad relativa','Humidité relative'],['Agua precipitable','Eau précipitable'],['Altura de la capa límite','Hauteur de la couche limite'],['Radiación solar descendente','Rayonnement solaire descendant'],['Radiación solar directa','Rayonnement solaire direct'],['Radiación térmica descendente','Rayonnement thermique descendant'],['Movimiento de células ordinarias','Déplacement des cellules ordinaires'],['Inhibición convectiva','Inhibition convective'],['Reflectividad simulada','Réflectivité simulée'],['Densidad de rayos','Densité de foudre'],['Nubosidad total','Nébulosité totale'],['Nubosidad baja','Nébulosité basse'],['Nubosidad alta','Nébulosité élevée'],['Helicidad relativa','Hélicité relative'],['Velocidad vertical en el NCL','Vitesse verticale au NCL'],['Helicidad de la corriente ascendente','Hélicité du courant ascendant']],
  it: [['Vorticidad absoluta a 850 hPa','Vorticità assoluta a 850 hPa'],['Vorticidad absoluta · Presión','Vorticità assoluta · Pressione'],['Intensidad potencial máxima (MPI)','Intensità potenziale massima (MPI)'],['Intensidad potencial · Presión','Intensità potenziale · Pressione'],['Índice de potencial de génesis (GPI)','Indice di potenziale di genesi (GPI)'],['Potencial de génesis · Presión','Potenziale di genesi · Pressione'],['y presión al nivel del mar','e pressione al livello del mare'],['Temperatura y geopotencial','Temperatura e geopotenziale'],['Temperatura a','Temperatura a'],['Temperatura de bulbo húmedo','Temperatura di bulbo umido'],['Viento por niveles','Vento per livelli'],['Racha máxima horaria','Raffica oraria massima'],['Cizalladura efectiva','Shear effettivo'],['Cizalladura','Wind shear'],['Precipitación acumulada','Precipitazione accumulata'],['Precipitación de nieve','Precipitazione nevosa'],['Precipitación en','Precipitazione in'],['Tipo de precipitación','Tipo di precipitazione'],['Humedad relativa','Umidità relativa'],['Agua precipitable','Acqua precipitabile'],['Altura de la capa límite','Altezza dello strato limite'],['Radiación solar descendente','Radiazione solare discendente'],['Radiación solar directa','Radiazione solare diretta'],['Radiación térmica descendente','Radiazione termica discendente'],['Movimiento de células ordinarias','Moto delle celle ordinarie'],['Inhibición convectiva','Inibizione convettiva'],['Reflectividad simulada','Riflettività simulata'],['Densidad de rayos','Densità dei fulmini'],['Nubosidad total','Nuvolosità totale'],['Nubosidad baja','Nuvolosità bassa'],['Nubosidad alta','Nuvolosità alta'],['Helicidad relativa','Elicità relativa'],['Velocidad vertical en el NCL','Velocità verticale al NCL'],['Helicidad de la corriente ascendente','Elicità della corrente ascendente']],
  pt: [['Vorticidad absoluta a 850 hPa','Vorticidade absoluta a 850 hPa'],['Vorticidad absoluta · Presión','Vorticidade absoluta · Pressão'],['Intensidad potencial máxima (MPI)','Intensidade potencial máxima (MPI)'],['Intensidad potencial · Presión','Intensidade potencial · Pressão'],['Índice de potencial de génesis (GPI)','Índice de potencial de génese (GPI)'],['Potencial de génesis · Presión','Potencial de génese · Pressão'],['y presión al nivel del mar','e pressão ao nível do mar'],['Temperatura y geopotencial','Temperatura e geopotencial'],['Temperatura a','Temperatura a'],['Temperatura de bulbo húmedo','Temperatura de bolbo húmido'],['Viento por niveles','Vento por níveis'],['Racha máxima horaria','Rajada horária máxima'],['Cizalladura efectiva','Cisalhamento efetivo'],['Cizalladura','Cisalhamento'],['Precipitación acumulada','Precipitação acumulada'],['Precipitación de nieve','Precipitação de neve'],['Precipitación en','Precipitação em'],['Tipo de precipitación','Tipo de precipitação'],['Humedad relativa','Humidade relativa'],['Agua precipitable','Água precipitável'],['Altura de la capa límite','Altura da camada limite'],['Radiación solar descendente','Radiação solar descendente'],['Radiación solar directa','Radiação solar direta'],['Radiación térmica descendente','Radiação térmica descendente'],['Movimiento de células ordinarias','Movimento de células comuns'],['Inhibición convectiva','Inibição convectiva'],['Reflectividad simulada','Refletividade simulada'],['Densidad de rayos','Densidade de raios'],['Nubosidad total','Nebulosidade total'],['Nubosidad baja','Nebulosidade baixa'],['Nubosidad alta','Nebulosidade alta'],['Helicidad relativa','Helicidade relativa'],['Velocidad vertical en el NCL','Velocidade vertical no NCL'],['Helicidad de la corriente ascendente','Helicidade da corrente ascendente']]
};

export function localizedForecastCategories(categories, language) {
  const labels = CATEGORY_LABELS[language];
  return labels ? categories.map((item, index) => ({ ...item, label: labels[index] })) : categories;
}

const SNOW_LEVEL_NAMES = {
  ca: 'Cota de neu', en: 'Snow level', de: 'Schneegrenze',
  fr: 'Limite pluie-neige', it: 'Quota neve', pt: 'Cota de neve'
};

const FREEZING_LEVEL_NAMES = {
  ca: 'Altura de la iso 0 °C', en: 'Freezing-level height',
  de: 'Höhe der Nullgradgrenze', fr: 'Altitude de l’isotherme 0 °C',
  it: 'Quota dello zero termico', pt: 'Altitude da isoterma de 0 °C'
};

export function localizedForecastProducts(products, language) {
  const replacements = LABEL_REPLACEMENTS[language];
  if (!replacements) return products;
  return products.map((item) => ({
    ...item,
    label: item.id === 'snow-level' || item.id === 'freezing-level'
      ? (item.id === 'snow-level' ? SNOW_LEVEL_NAMES : FREEZING_LEVEL_NAMES)[language] || item.label
      : replacements.reduce((text, [from, to]) => text.replace(from, to), item.label),
    short: item.id === 'snow-level' ? SNOW_LEVEL_NAMES[language] || item.short : item.short,
    contents: item.contents
      ? replacements.reduce((text, [from, to]) => text.replace(from, to), item.contents)
      : item.contents
  }));
}

const LAYER_LABELS = {
  es: { isotherms: 'Isotermas', isohypses: 'Isohipsas', troughs: 'Ejes de vaguada', centres: 'Centros de presión', cities: 'Ciudades', isobars: 'Isobaras', isentropes: 'Isentrópicas' },
  ca: { isotherms: 'Isotermes', isohypses: 'Isohipses', troughs: 'Eixos de vaguada', centres: 'Centres de pressió', cities: 'Ciutats', isobars: 'Isòbares', isentropes: 'Isentròpiques' },
  en: { isotherms: 'Isotherms', isohypses: 'Height contours', troughs: 'Trough axes', centres: 'Pressure centres', cities: 'Cities', isobars: 'Isobars', isentropes: 'Isentropes' },
  de: { isotherms: 'Isothermen', isohypses: 'Isohypsen', troughs: 'Trogachsen', centres: 'Druckzentren', cities: 'Städte', isobars: 'Isobaren', isentropes: 'Isentropen' },
  fr: { isotherms: 'Isothermes', isohypses: 'Isohypses', troughs: 'Axes de thalweg', centres: 'Centres de pression', cities: 'Villes', isobars: 'Isobares', isentropes: 'Isentropes' },
  it: { isotherms: 'Isoterme', isohypses: 'Isoipse', troughs: 'Assi di saccatura', centres: 'Centri di pressione', cities: 'Città', isobars: 'Isobare', isentropes: 'Isentrope' },
  pt: { isotherms: 'Isotérmicas', isohypses: 'Isoípsas', troughs: 'Eixos de cavado', centres: 'Centros de pressão', cities: 'Cidades', isobars: 'Isóbaras', isentropes: 'Isentrópicas' }
};

const MULTIPLE_LABELS = {
  es: 'Zonas con varias soluciones', ca: 'Zones amb diverses solucions',
  en: 'Multiple altitude solutions', de: 'Mehrere Höhenlösungen',
  fr: 'Plusieurs altitudes possibles', it: 'Più quote possibili',
  pt: 'Várias cotas possíveis'
};

const SNOW_CONTOUR_LABELS = {
  es: 'Isolíneas de cota de nieve', ca: 'Isolínies de cota de neu',
  en: 'Snow-level contours', de: 'Schneegrenzen-Isolinien',
  fr: 'Isolignes de limite pluie-neige', it: 'Isolinee della quota neve',
  pt: 'Isolinhas da cota de neve'
};

const FREEZING_CONTOUR_LABELS = {
  es: 'Isolíneas de altura de la iso 0 °C', ca: 'Isolínies d’altura de la iso 0 °C',
  en: 'Freezing-level contours', de: 'Isolinien der Nullgradgrenze',
  fr: 'Isolignes de hauteur de l’isotherme 0 °C', it: 'Isolinee dello zero termico',
  pt: 'Isolinhas da altitude da isoterma de 0 °C'
};

const LI_CONTOUR_LABELS = {
  es: 'Isopletas de LI', ca: 'Isopletes de LI', en: 'LI contours',
  de: 'LI-Isolinien', fr: 'Isoplèthes du LI', it: 'Isoplete del LI',
  pt: 'Isopletas do LI'
};

export function forecastLayerLabel(language, id, fallback) {
  if (id === 'liContours') return LI_CONTOUR_LABELS[language] || LI_CONTOUR_LABELS.es;
  if (id === 'multipleSolutions') return MULTIPLE_LABELS[language] || MULTIPLE_LABELS.es;
  if (id === 'snowContours') return SNOW_CONTOUR_LABELS[language] || SNOW_CONTOUR_LABELS.es;
  if (id === 'freezingContours') return FREEZING_CONTOUR_LABELS[language] || FREEZING_CONTOUR_LABELS.es;
  return (LAYER_LABELS[language] || LAYER_LABELS.es)[id] || fallback;
}


// Nombres de los dominios y zonas del selector, por idioma. Sin traducción,
// el nombre en castellano del registro.
const DOMAIN_LABELS = {
  ca: { full: 'Domini complet', iberia: 'Península Ibèrica', france: 'França', italy: 'Itàlia', alps: 'Suïssa i Àustria', 'british-isles': 'Illes Britàniques', 'benelux-germany': 'Benelux i Alemanya', europe: 'Europa i Atlàntic', 'middle-east': 'Orient Mitjà i Àsia central', 'north-america': 'Amèrica del Nord', 'east-asia': 'Àsia oriental i Pacífic', 'south-america': 'Amèrica del Sud', australia: 'Austràlia i Nova Zelanda' },
  en: { full: 'Full domain', iberia: 'Iberian Peninsula', france: 'France', italy: 'Italy', alps: 'Switzerland and Austria', 'british-isles': 'British Isles', 'benelux-germany': 'Benelux and Germany', europe: 'Europe and Atlantic', 'middle-east': 'Middle East and Central Asia', 'north-america': 'North America', 'east-asia': 'East Asia and Pacific', 'south-america': 'South America', australia: 'Australia and New Zealand' },
  de: { full: 'Gesamtes Gebiet', iberia: 'Iberische Halbinsel', france: 'Frankreich', italy: 'Italien', alps: 'Schweiz und Österreich', 'british-isles': 'Britische Inseln', 'benelux-germany': 'Benelux und Deutschland', europe: 'Europa und Atlantik', 'middle-east': 'Naher Osten und Zentralasien', 'north-america': 'Nordamerika', 'east-asia': 'Ostasien und Pazifik', 'south-america': 'Südamerika', australia: 'Australien und Neuseeland' },
  fr: { full: 'Domaine complet', iberia: 'Péninsule Ibérique', france: 'France', italy: 'Italie', alps: 'Suisse et Autriche', 'british-isles': 'Îles Britanniques', 'benelux-germany': 'Benelux et Allemagne', europe: 'Europe et Atlantique', 'middle-east': 'Moyen-Orient et Asie centrale', 'north-america': 'Amérique du Nord', 'east-asia': 'Asie orientale et Pacifique', 'south-america': 'Amérique du Sud', australia: 'Australie et Nouvelle-Zélande' },
  it: { full: 'Dominio completo', iberia: 'Penisola Iberica', france: 'Francia', italy: 'Italia', alps: 'Svizzera e Austria', 'british-isles': 'Isole Britanniche', 'benelux-germany': 'Benelux e Germania', europe: 'Europa e Atlantico', 'middle-east': 'Medio Oriente e Asia centrale', 'north-america': 'Nord America', 'east-asia': 'Asia orientale e Pacifico', 'south-america': 'Sud America', australia: 'Australia e Nuova Zelanda' },
  pt: { full: 'Domínio completo', iberia: 'Península Ibérica', france: 'França', italy: 'Itália', alps: 'Suíça e Áustria', 'british-isles': 'Ilhas Britânicas', 'benelux-germany': 'Benelux e Alemanha', europe: 'Europa e Atlântico', 'middle-east': 'Médio Oriente e Ásia central', 'north-america': 'América do Norte', 'east-asia': 'Ásia oriental e Pacífico', 'south-america': 'América do Sul', australia: 'Austrália e Nova Zelândia' }
};

export function forecastDomainLabel(language, domain) {
  return DOMAIN_LABELS[language]?.[domain.id] || domain.label;
}
